on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      redis:
        image: redis
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Connect to Redis
      run: node client.js
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379
    - name: Make the Maven Wrapper Executable
      run: chmod +x mvnw
    - name: Use the Maven Wrapper to Test
      run: ./mvnw -q test
    - name: Curl Codecov
      if: ${{ success() }}
      run: bash <(curl -s https://codecov.io/bash)
    - name: Cache .m2/repository
      uses: actions/cache@v3
      with:
          key: ${{ runner.os }}-m2-repository
          path: $HOME/.m2/repository
      
